# Use an official Python runtime as a parent image
FROM python:3.10.14

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --upgrade pip 
RUN pip3 install --trusted-host pypi.python.org -r requirements.txt --user

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable
ENV FLASK_APP=server.py
ENV FLASK_RUN_HOST=0.0.0.0

#write the CMD command using python to run server.py
CMD ["python", "server.py"]
